### ISSUE TITLE
trained model file 

### ISSUE THREAD

**Issue by hemant-1332** [agrawal-rohit/twitter-sentiment-analysis-web-app#2]
File _'main_app/Sentiment_LSTM_model.h5'_ is just 1KB after cloning. How can I get the complete trained model ?

**Comment by Rodio346** [comment]
Faced the same issue while cloning 
What you do is 
1. Go to the below URL:
https://www.kaggle.com/thatawkwardguy/twitter-sentiment-classification-using-cnns
""Its a kaggle worksheet ""
2. Go in the output section 
3. There you will find your Sentiment_LSTM_model.h5
4. place it in main_app

**Comment by shivam-0** [comment]
@Rodio346 bro can you pls help me out for this project
