### ISSUE TITLE
server not working

### ISSUE THREAD

**Issue by murtazaali1999** [agrawal-rohit/twitter-sentiment-analysis-web-app#25]
I'm trying to hit localhost 8000 but it doesn't seem to respond.
See if you can spot the error in the media ?
The server doesn't seem to be running after the docker image is made . Need help ASAP

I followed these steps
### Running the application

1. Download the [trained model](https://drive.google.com/file/d/1ckK5m4JysFKtBuC9yCnEaHe6cxOgXlG8/view?usp=sharing) and put into the `server/main` folder <br>(**Note:** _This is the CNN model. if you want use the LSTM model, you'll need to follow the [training steps](#training-the-model) below and put the saved model in `server/main`. Also, don't forget to change the loaded model name in `server/main/init.py`_ )

2. Get your Twitter API credentials through Keys and Tokens tab under the [Twitter Developer Portal Projects & Apps page](https://developer.twitter.com/en/portal/projects-and-apps) and add them to the `/server/main/config.py` file.

3. Run `docker-compose up --build` in the terminal from the root folder <br> (**Note:** _Ensure that you have Docker installed_)

4. Open `http://localhost:5000` in your browser to access the app

![port](https://user-images.githubusercontent.com/61330248/191437496-9d63f36d-46ee-4d46-b63f-e70ac76fba91.PNG)
![dep1](https://user-images.githubusercontent.com/61330248/191437502-f3369aec-0889-4bbf-960d-0148d23bb1c2.PNG)
![ev11](https://user-images.githubusercontent.com/61330248/191437504-3652916a-ba22-493b-8cdb-e6cbff782281.PNG)

**Comment by agrawal-rohit** [comment]
Did you enter valid Twitter API credentials into the server config file? 

Also, Please send the error message in the server logs

**Comment by shivams07** [comment]
I did try to update the compose yaml file to uncomment the Server section code and it worked for me.

version: "2"

services:
    server:
      build: ./server/
      command: >
        gunicorn -b 0.0.0.0:8000 --access-logfile - --reload "main:app"
      volumes:
        - ./server:/app
      ports:
        - 8000:8000

    client:
      build: ./client/
      command: npm run start
      volumes:
        - ./client:/app
        - /app/node_modules
      ports:
        - 3000:3000

**Comment by murtazaali1999** [comment]
The issue seems to be an issue in gunicorn and the docker server, I
don't know the conflict its causing,
gunicorn -b 0.0.0.0:8000 --access-logfile - --reload "main:app"

Another question, after the --access-logfile do I have to specify the
gunicorn file directory

The image is the problem that is being caused by gunicorn:

[image: WhatsApp Image 2022-10-12 at 2.19.32 PM.jpeg]

**Comment by zubairfazalkhan** [comment]
I have changed the compose yaml file as @shivams07 said but got this error

Attaching to twitter-sentiment-analysis-client-1, twitter-sentiment-analysis-server-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gunicorn": executable file not found in $PATH: unknown

**Comment by agrawal-rohit** [comment]
@murtazaali1999 Could you attach the image again? I can't seem to view it.

@zubairfazalkhan I haven't encountered this error before, even when working with a different OS (Mac or Windows). Did you try to google this error?

**Comment by murtazaali1999** [comment]
![191437496-9d63f36d-46ee-4d46-b63f-e70ac76fba91](https://user-images.githubusercontent.com/61330248/198679328-3b17d39b-960e-40e0-81c9-6447b94b0d90.png)
![191437502-f3369aec-0889-4bbf-960d-0148d23bb1c2](https://user-images.githubusercontent.com/61330248/198679333-6ae929c0-e17b-4cb8-b6df-6d4423fe0ef6.png)
![191437504-3652916a-ba22-493b-8cdb-e6cbff782281](https://user-images.githubusercontent.com/61330248/198679340-53073a99-0534-45d9-8f28-110dba99554c.png)

@agrawal-rohit Re-Uploaded

**Comment by ghodkeyashraj30** [comment]
I am having the same error that the server not working...

**Comment by ghodkeyashraj30** [comment]
![Screenshot (112)](https://user-images.githubusercontent.com/78252070/205559319-e266f6b1-ff56-4b4f-9d5a-f21f95cd2f9c.png)

**Comment by zubairfazalkhan** [comment]
@agrawal-rohit I am still getting error, client site and server site both are working now but when i give the text i got this
<img width="1280" alt="Screenshot 2023-01-01 at 23 07 52" src="https://user-images.githubusercontent.com/59198335/210180578-8f76dc10-4849-4926-9149-d81c9d55aa34.png">
