### ISSUE TITLE
Endless loop in running http://localhost:3000/ via npm

### ISSUE THREAD

**Issue by tobimichigan** [agrawal-rohit/twitter-sentiment-analysis-web-app#26]
Hi there. Nice repo. 
I successfully built and ran your code locally with the help of docker-ce and npm.I would soon pull your repo and help rewrite the install procedures. In the meantime, please could you suggest the reason why after typing a tweet query in the input box, the app continues a a looped condition or interface without going forward.

![image](https://user-images.githubusercontent.com/5084987/200582277-31a10d31-0eaf-4e8b-980f-30b9c2435292.png)
and
![image](https://user-images.githubusercontent.com/5084987/200582451-a78e37cf-918c-45ec-adda-e79e8313ecbd.png)

Please kindly advise...

**Comment by agrawal-rohit** [comment]
Check the server container logs if the API throwing an error. It could be due to incorrect Twitter API credentials, Twitter API changes (#28) , etc.

**Comment by agrawal-rohit** [comment]
I've fixed the issues regarding the docker containers, python dependencies, and the deprecated Twitter API. The project should work correctly through docker now, Please refer to the README for the updated steps to spin up the project 😇
