### ISSUE TITLE
Twitter Error 403

### ISSUE THREAD

**Issue by devansh016** [agrawal-rohit/twitter-sentiment-analysis-web-app#28]
[2022-11-23 20:32:50 +0000] [9] [ERROR] Error handling request /analyzehashtag?text=elon
twitter-sentiment-analysis-web-app-server-1  | Traceback (most recent call last):
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
twitter-sentiment-analysis-web-app-server-1  |     self.handle_request(listener, req, client, addr)
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request      
twitter-sentiment-analysis-web-app-server-1  |     respiter = self.wsgi(environ, resp.start_response)
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
twitter-sentiment-analysis-web-app-server-1  |     return self.wsgi_app(environ, start_response)
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
twitter-sentiment-analysis-web-app-server-1  |     response = self.handle_exception(e)
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function     
twitter-sentiment-analysis-web-app-server-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
twitter-sentiment-analysis-web-app-server-1  |     reraise(exc_type, exc_value, tb)
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
twitter-sentiment-analysis-web-app-server-1  |     raise value
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
twitter-sentiment-analysis-web-app-server-1  |     response = self.full_dispatch_request()
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
twitter-sentiment-analysis-web-app-server-1  |     rv = self.handle_user_exception(e)
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function     
twitter-sentiment-analysis-web-app-server-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
twitter-sentiment-analysis-web-app-server-1  |     reraise(exc_type, exc_value, tb)
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
twitter-sentiment-analysis-web-app-server-1  |     raise value
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
twitter-sentiment-analysis-web-app-server-1  |     rv = self.dispatch_request()
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
twitter-sentiment-analysis-web-app-server-1  |     return self.view_functions[rule.endpoint](**req.view_args)
twitter-sentiment-analysis-web-app-server-1  |   File "/app/main/__init__.py", line 77, in analyzehashtag
twitter-sentiment-analysis-web-app-server-1  |     for tweet in tweepy.Cursor(api.search,q="#" + request.args.get("text") + " -filter:retweets",rpp=5,lang="en", tweet_mode='extended').items(100):
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/tweepy/cursor.py", line 49, in __next__
twitter-sentiment-analysis-web-app-server-1  |     return self.next()
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/tweepy/cursor.py", line 197, in next
twitter-sentiment-analysis-web-app-server-1  |     self.current_page = self.page_iterator.next()
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/tweepy/cursor.py", line 108, in next
twitter-sentiment-analysis-web-app-server-1  |     data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/tweepy/binder.py", line 250, in _call
twitter-sentiment-analysis-web-app-server-1  |     return method.execute()
twitter-sentiment-analysis-web-app-server-1  |   File "/opt/venv/lib/python3.6/site-packages/tweepy/binder.py", line 234, in execute
twitter-sentiment-analysis-web-app-server-1  |     raise TweepError(error_msg, resp, api_code=api_error_code)
twitter-sentiment-analysis-web-app-server-1  | tweepy.error.TweepError: Twitter error response: status code = 403
twitter-sentiment-analysis-web-app-server-1  | 172.18.0.1 - - [23/Nov/2022:20:32:50 +0000] "GET /analyzehashtag?text=elon HTTP/1.1" 500 0 "-" "-"

**Comment by devansh016** [comment]
I followed all the steps in the readme file.

**Comment by devansh016** [comment]
Got the problem twitter API got depreciated.

**Comment by agrawal-rohit** [comment]
@devansh016 I've updated the repo to support the new Twitter API, along with the correct credentials required. Please refer to the README for the updated steps to spin up the project
