### ISSUE TITLE
project not working

### ISSUE THREAD

**Issue by shivam-0** [agrawal-rohit/twitter-sentiment-analysis-web-app#7]
After runing install all the npm and python requirements,using python manage.py runserver to run the server the analysis work for maximum of 2-3 times and after that it stops working ..and that too is completely random . 
the only error it shows is some sort of Error: manifest.json not found  
if somebody is willing to help ..pls do help me out

**Comment by agrawal-rohit** [comment]
The link between the frontend and backend is not very efficient, I agree. It was just made for testing out the app.

**Comment by agrawal-rohit** [comment]
Are you referring to this manifest.json file? https://github.com/agrawal-rohit/twitter-sentiment-analysis-web-app/blob/master/react-frontend/public/manifest.json

**Comment by shivam-0** [comment]
@agrawal-rohit App is making thousands of request to to the Twitter api to get tweets..which is overloading it in some way and the app can't work for more than 2-3 times..

**Comment by agrawal-rohit** [comment]
Hey, the problems have now been fixed. Please open another issue know if this problem persists

PS: Sorry for the late reply
